Fix startup under Python2
While geventmp works with Python3, under Python2 it fails at activation
stage due to erroneous import, because _mp is located under geventmp (not "mp"
suffix) package, not gevent:

    (neo) (z-dev) (g.env) kirr@deco:~/src/tools/go/pygolang$ gpython
    Traceback (most recent call last):
      File "/home/kirr/src/wendelin/venv/z-dev/bin/gpython", line 3, in <module>
        from gpython import main; main()
      File "/home/kirr/src/tools/go/pygolang/gpython/__init__.py", line 190, in main
        _ = monkey.patch_all(thread=patch_thread)      # XXX sys=True ?
      File "/home/kirr/src/wendelin/venv/z-dev/local/lib/python2.7/site-packages/gevent/monkey.py", line 966, in patch_all
        _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
      File "/home/kirr/src/wendelin/venv/z-dev/local/lib/python2.7/site-packages/gevent/monkey.py", line 168, in _notify_patch
        notify_and_call_entry_points(event)
      File "/home/kirr/src/wendelin/venv/z-dev/local/lib/python2.7/site-packages/gevent/events.py", line 113, in notify_and_call_entry_points
        subscriber(event)
      File "/home/kirr/src/tools/py/gevent/geventmp/src/geventmp/monkey.py", line 142, in _patch_mp
        _mp = import_module("gevent._mp.2_7.__mp")
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named _mp.2_7.__mp

Fix it.